### ISSUE TITLE
to_dict() got an unexpected keyword argument 'orient'

### ISSUE THREAD

**Issue by aneesha** [bmabey/pyLDAvis#10]
Hi

I'm getting the following error on ubuntu

to_dict() got an unexpected keyword argument 'orient'

Exception Type:	TypeError
Exception Value:	
to_dict() got an unexpected keyword argument 'orient'
Exception Location:	/usr/local/lib/python2.7/dist-packages/pyLDAvis/_prepare.py in to_dict, line 303

Thanks for helping

**Comment by bmabey** [comment]
Upgrading pandas should fix this.

**Comment by aneesha** [comment]
Many thanks for the prompt response - a pandas update fixed the issue. 

Also just wanted to let you know that I am using pyLDAvis outside of an ipython notebook, in a web app and its working great.

**Comment by bmabey** [comment]
Sweet, thanks for the experience report!
