### ISSUE TITLE
Need upgrade for d3.js .. need d3.v4.js

### ISSUE THREAD

**Issue by msusol** [bmabey/pyLDAvis#120]
I am not able to use this package anymore until it renders using d3.v4.js.

Any plans to update this package?

**Comment by bmabey** [comment]
I don't plan on updating it myself but would merge in a PR.

**Comment by dtemkin** [comment]
@msusol Just submitted a PR with changes that work with d3.v5.js I haven't tried it with v4 but all the changes I made were the result of the v4 release so you are more than welcome to give my fork a try. If you do let me know how it goes.

**Comment by msusol** [comment]
Let's move on d3.v5.js then. at the time I created this, we were only at d3.v3 -> d3.v4 transition.

**Comment by msusol** [comment]
See follow up refactoring: #198
