### ISSUE TITLE
`pyLDAvis.gensim` needs to be imported explicitly

### ISSUE THREAD

**Issue by martin-martin** [bmabey/pyLDAvis#131]
I keep getting `AttributeError` when attempting to run:

```
import pyLDAvis

# ... creating LDA model, corpus, and dictionary in here
pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)
```

Here's the traceback:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-950ae09ed90b> in <module>()
----> 1 pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)

AttributeError: module 'pyLDAvis' has no attribute 'gensim'
```

---

However, the code runs fine when importing `gensim` explicitly:

```
from pyLDAvis import gensim

# ... same as above
gensim.prepare(ldamodel, corpus, dictionary)
```

Unsure why that would be the case? Is it possible that `gensim` would need to be added to [`__init__.py`](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/__init__.py)?

**Comment by priyaananthasankar** [comment]
How about this: `import pyLDAvis.gensim` This doesn't give me Attribute Error

**Comment by MayKT** [comment]
import pyLDAvis.gensim gives me import error. How can i solve it?

**Comment by MayKT** [comment]
> How about this: `import pyLDAvis.gensim` This doesn't give me Attribute Error

**Comment by anandi1989** [comment]
> import pyLDAvis.gensim gives me import error. How can i solve it?

Looks like this is latest issue with version 3.3.0 

Switch to version 3.2.2 and it will work like charm.

**Comment by msusol** [comment]
vs3.3.0 had to rename the file name, so now use `import pyLDAvis.gensim_models`

**Comment by anandi1989** [comment]
> vs3.3.0 had to rename the file name, so now use `import pyLDAvis.gensim_models`
> 
> Note: the colab examples have `import pyLDAvis.gensim AS gensimvis`, and I could rename the file to `gensimvis.py` then it would simply be `import pyLDAvis.gensimvis`

Thanks for the quick action.

**Comment by VictorSuarezL** [comment]
Still have the same problem. Any tips?

**Comment by anandi1989** [comment]
> Still have the same problem. Any tips?

change the version to ```pyLDAvis==3.2.1```

**Comment by Briceken** [comment]
hello everyone.
I'm using python 3.9.12 and have the same Error  whith : import pyLDAvis.gensim

I solve it  by using  : import pyLDAvis.gensim_models

I still don't know why but it work.

**Comment by 907Resident** [comment]
> hello everyone. I'm using python 3.9.12 and have the same Error with : import pyLDAvis.gensim i also try : from pyLDAvis import gensim but don't work
> 
> I solve it by importing the package gensim_models instead of gensim : import pyLDAvis.gensim_models
> 
> I still don't understand why but it work.

Yes, this worked for me as well. Unfortunately, I do not know the reason but I found the answer with further explanation on stack: https://stackoverflow.com/a/71920375

**Comment by ChathuraGal** [comment]
> hello everyone. I'm using python 3.9.12 and have the same Error with : import pyLDAvis.gensim i also try : from pyLDAvis import gensim but don't work
> 
> I solve it by importing the package gensim_models instead of gensim : import pyLDAvis.gensim_models
> 
> I still don't understand why but it work.

It worked for me too

**Comment by msusol** [comment]
> I solve it by importing the package gensim_models instead of gensim : import pyLDAvis.gensim_models
>
> I still don't understand why but it work.

https://github.com/bmabey/pyLDAvis/issues/131#issuecomment-805164485
