### ISSUE TITLE
It does not work well with pyinstaller 

### ISSUE THREAD

**Issue by AshishDhadwal** [bmabey/pyLDAvis#142]
I created an exe for LDA topic modelling .It works fine in my system but when created exe using pyinstaller  it got stuck and does not respond .I also added datas to .spec file but still no response in exe .
below is my code :
`dash = pyLDAvis.sklearn.prepare(lda, data_vectorized, vectorizer, mds='tsne')
    pyLDAvis.save_html(dash,file)`

**Comment by binProg** [comment]
Hello, I have encountered the same problem. Do you have a solution to it?

**Comment by msusol** [comment]
Obsoleting.. please reevaluate the issue with v3.3.0 and create a new issue/PR for testing.
