### ISSUE TITLE
jupyter notebook doesn't remember pyLDAvis.prepare()

### ISSUE THREAD

**Issue by sandgate-dev** [bmabey/pyLDAvis#143]
When executing the cell 

```
pyLDAvis.sklearn.prepare(lda_tf, dtm_tf, tf_vectorizer)
```

 it displays the graph but after saving the notebook and reopen it, it shows nothing.

I have the following imports/setting:

```
import pyLDAvis
import pyLDAvis.gensim
import pyLDAvis.sklearn
pyLDAvis.enable_notebook()
```
`print(pyLDAvis.__version__)` -> 2.1.2

Anaconda environment: Python 3.6 and ipython 7.2.0.

Thanks for the help.

**Comment by osterburg** [comment]
This is what prepare gives me:
```
/anaconda3/envs/learnco_projects/lib/python3.6/site-packages/pyLDAvis/_prepare.py:257: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  return pd.concat([default_term_info] + list(topic_dfs))
```

**Comment by osterburg** [comment]
I downloaded
`https://nbviewer.jupyter.org/github/bmabey/pyLDAvis/blob/master/notebooks/sklearn.ipynb`
but the output for the graph shows also empty.
I compared this notebook with what I am working on and the area for the output from pyLDAvis are pretty much the same.
