### ISSUE TITLE
A result has failed to un-serialize. Ensure objects are picklable

### ISSUE THREAD

**Issue by hyonschu** [bmabey/pyLDAvis#144]
pyLDAvis.__version__: 2.1.2
pd.__version__: 0.23.4

`pyLDAvis.enable_notebook()`
`vis = pyLDAvis.gensim.prepare(lda_model, corpus, id2word, sort_topics=0)`

returns
`ModuleNotFoundError: No module named 'pandas.core.internals.managers'; 'pandas.core.internals' is not a package` 
and 
`joblib.externals.loky.process_executor.BrokenProcessPool: A result has failed to un-serialize. Please ensure that the objects returned by the function are always picklable.`

**Comment by hyonschu** [comment]
2.1.1 works with DeprecationWarning for .ix

**Comment by phonosync** [comment]
Hi,
I think these are two separate issues.

1. The ModuleNotFoundError I can not reproduce with the package versions pyLDAvis.version: 2.1.2 and pd.version: 0.24.2
2. I get the same error on Windows 10, Python 3.7.4 and pyLDAvis 2.1.2:

joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

And I believe the underlying problem with Loky is documented here: https://github.com/joblib/joblib/issues/810

When I force to use multiprocessing as the joblib backend, the error disappears. I opened a pull request #156 
Let's see...

Best regards,
Manuel

**Comment by Liza23** [comment]
You can try this. I'm not sure if it'll work for you but it did for me so:)
`!pip install --upgrade pandas==1.2`
