### ISSUE TITLE
2.1.3 release to PyPI?

### ISSUE THREAD

**Issue by ned2** [bmabey/pyLDAvis#147]
I was investigating what would be involved in submitting a PR to silence the `FutureWarning` that Pandas is throwing when calling `prepare()` but see that it was already fixed in #133. It would be good to have that fix along with the other changes in 2.1.3 available on PyPI.

I'd be happy to help if there's anything I can do to make that happen.

**Comment by msusol** [comment]
Please see recent release (v3.3.0) and if still an issue create a new issue with current details.
