### ISSUE TITLE
In v2.1.2, pyLDAvis.gensim.prepare() is throwing "index out of bounds" error

### ISSUE THREAD

**Issue by polars05** [bmabey/pyLDAvis#153]
Hi, I'm getting the following error when I run pyLDAvis.gensim.prepare(): 

> IndexError: index 70987 is out of bounds for axis 1 with size 70987

My code is as follows:
```python
model = gensim.models.ldamodel.LdaModel.load('gensim_lda/lda.model')

for i in range(0, model.num_topics-1):
	print ("########## topix %d ##########" %i)
	print (model.print_topic(i))
	print ("####################")

dictionary_loaded = corpora.Dictionary.load("test_dict.pkl")
corpus_loaded = corpora.MmCorpus('test_corpus.mm')

vis_data = pyLDAvis.gensim.prepare(model, corpus_loaded, dictionary_loaded)
pyLDAvis.display(vis_data)
pyLDAvis.save_html(vis_data, "test.html")
```

I saw that similar issues have been raised in #124 and #72 previously; @bmabey mentioned that this has been fixed in v.2.1.1 back in Feb 2017. However, I'm currently using v2.1.2 and still observing this issue. Any advice pls? Thanks!

**Comment by showkeyjar** [comment]
+1

**Comment by searri** [comment]
I'm also experiencing this problem in LDAvis v2.1.2.

@polars05 Did you happen to find a solution or are you still having the issue?

**Comment by msusol** [comment]
Obsoleting.. please reevaluate the issue with v3.3.0 and create a new issue/PR for testing.
