### ISSUE TITLE
PyLDAvis IndexError: index 135678 is out of bounds for axis 1 with size 135678

### ISSUE THREAD

**Issue by SaharNasiri** [bmabey/pyLDAvis#155]
Hi,

I used PyLDAvis to visualize my gensim topic modeling result, but I am getting an IndexError says: index 135678 is out of bounds for axis 1 with size 135678. My PyLDAvis version is 2.1.2, and I tried it with the different dataset and it is working but I don't know why it is not working now? It seems an issue with the library! Here is my code:

from gensim.models import LdaModel
model = LdaModel.load('model.lda')

pickle_in = open("processed_data.pickle","rb")
data = pickle.load(pickle_in)

id2word = corpora.Dictionary(data)
texts = data
corpus = [id2word.doc2bow(text) for text in texts]

# Visualize the topics
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(model, corpus, id2word)

and the error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-89a10220bfcb> in <module>
      1 # Visualize the topics
      2 pyLDAvis.enable_notebook()
----> 3 vis = pyLDAvis.gensim.prepare(model, corpus, id2word)
      4 pyLDAvis.save_html(vis, 'data.html')

/software/python3/3.7.1/lib/python3.7/site-packages/pyLDAvis/gensim.py in prepare(topic_model, corpus, dictionary, doc_topic_dist, **kwargs)
    116     See `pyLDAvis.prepare` for **kwargs.
    117     """
--> 118     opts = fp.merge(_extract_data(topic_model, corpus, dictionary, doc_topic_dist), kwargs)
    119     return vis_prepare(**opts)

/software/python3/3.7.1/lib/python3.7/site-packages/pyLDAvis/gensim.py in _extract_data(topic_model, corpus, dictionary, doc_topic_dists)
     46           gamma = topic_model.inference(corpus)
     47       else:
---> 48           gamma, _ = topic_model.inference(corpus)
     49       doc_topic_dists = gamma / gamma.sum(axis=1)[:, None]
     50    else:

/software/python3/3.7.1/lib/python3.7/site-packages/gensim/models/ldamodel.py in inference(self, chunk, collect_sstats)
    678             Elogthetad = Elogtheta[d, :]
    679             expElogthetad = expElogtheta[d, :]
--> 680             expElogbetad = self.expElogbeta[:, ids]
    681 
    682             # The optimal phi_{dwk} is proportional to expElogthetad_k * expElogbetad_w.

IndexError: index 135678 is out of bounds for axis 1 with size 135678

**Comment by PartsUnknown** [comment]
Was this resolved?  I am getting a similar error.  Everything was working as expected, but then after a restart nothing works.

**Comment by msusol** [comment]
Please update to pyLDAvis vs 3.2.2 and if you still have issues, post a new issue for triage.

**Comment by anthoskountouris** [comment]
Was this resolved? I am getting a similar error.
