### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by sydneymwong** [bmabey/pyLDAvis#16]
Hi bmabey, if I import gensim and import pyLDAvis.gensim at the top of my file, and then later on I call gensim.models.ldamodel.LdaModel(), I get deprecation warnings.  But if I import gensim, then call LdaModel(), then import pyLDAvis, I do not get any deprecation warnings.  It's not a big deal but I just thought you'd like to know.  I love pyLDAvis by the way, I was doing my preprocessing in Python and then using R for the lda and visualization before finding pyLDAvis.

**Comment by bmabey** [comment]
Many of these warnings I believe should be resolved with the latest version I just released.
