### ISSUE TITLE
pyLDAvis causing Button Icons to disappear in Jupyter Lab

### ISSUE THREAD

**Issue by andyhegedus** [bmabey/pyLDAvis#162]
Hi,
Have been working with the folks at Jupyter Lab on an issue of icon buttons disappearing.  There is strong evidence that it is an interaction with pyLDAvis.

https://github.com/jupyterlab/jupyterlab/issues/7959#issuecomment-594903638

Since Jupyter Labs is the plan going forward it would be nice that everything worked and played well together.
Andy

**Comment by andyhegedus** [comment]
What has been identified is when the pyLDAvis visualization is presented in a Jupyter Lab session it causes the toolbar buttons to disappear.
<img width="876" alt="gone" src="https://user-images.githubusercontent.com/44418310/75931149-1fe51b80-5e29-11ea-9e0a-0e0e9b1df1a1.png">

compared to as expected.
<img width="872" alt="while running" src="https://user-images.githubusercontent.com/44418310/75931229-528f1400-5e29-11ea-9b14-1b2cc48f81f2.png">

This is reproducible on several machines.
Test system are Mac OS X with either Safari or Chrome as the host browser.
Andy

**Comment by telamonian** [comment]
Hi, I'm one of the jupyterlab devs. To be clear, unlike what it says in #121 it seems like `.display()` does work in the newly-released jupyterlab 2.0.0. It just [renders most of our icons invisible](https://github.com/jupyterlab/jupyterlab/issues/7959#issuecomment-594895888):

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/2263641/75931158-48c5da80-5e42-11ea-9c3a-e09764e024c8.png">

These appear to be the offending lines:

https://github.com/bmabey/pyLDAvis/blob/a108b0c6458012e17d0d0f8a5b09015e17201982/pyLDAvis/js/ldavis.css#L5-L8

So long as a cell containing a pyLDAvis visualization is present in any open notebook, that stylesheet gets loaded on the page, which hides all of the `<path>` elements inside of our `<svg>` icons. Deleting/hiding the cell, or closing the notebook, unloads the stylesheet and "fixes" the problem.

I'm actually really curious about how that stylesheet is getting so dynamically injected

**Comment by jasongrout** [comment]
I'll add that those CSS lines are so overly broad that it's a wonder this hasn't caused problems up to this point. My guess is that narrowing that CSS down to where you actually want it applied would be a good first step.

**Comment by robroc** [comment]
Just want to add a "me too" here. Sine installing pyLDAvis, the buttons in Jupyter Lab are getting hidden. On Chrome and Firefox.

**Comment by MarcMeketonVillanova** [comment]
I have not installed pyLDAvis.  On my 'base' environment I do not see the toolbar buttons, but in other virtual environments I do see them.  I assume something similar is going on.

**Comment by jasongrout** [comment]
If you don't have pyLDAvis installed, then it's probably not this issue. Would you file a [new issue](https://github.com/jupyterlab/jupyterlab/issues/new?template=bug_report.md) with JupyterLab and fill in the info requested in the issue template there?

**Comment by quillan86** [comment]
Still having this issue witht pyLDAvis.

**Comment by schiffpierre** [comment]
I am also encountering this exact same issue when enabling pyLDAvis in JupyterLab.

**Comment by andyhegedus** [comment]
I have come up with a work around.
Instead on viewing the visualization inline within Jupyter notebook, save the result to an HTML file and view in a separate tab.
Normally I would do this:
vis = pyLDAvis.gensim.prepare(lda_model_tfidf, corpus, dictionary=lda_model_tfidf.id2word)
vis
where the vis command inserts the visualization.
Instead use the save html command to save it a file and then open that file is a separate tab.
pyLDAvis.save_html(vis, "/........./Desktop/top_5_topicsb.html")
Andy

**Comment by bsherin** [comment]
I just wanted to add another me too. I'm the developer for another environment [Tactic Text](https://github.com/bsherin/tactic) and I'm having the same issue. All of my buttons disappear whenever the pyLDAvis styles get loaded.

**Comment by johnjdailey** [comment]
Same issue, in Jupyter Lab, no buttons after running pyLDAvis, somewhere between:

**Comment by MarcMeketonVillanova** [comment]
I had this problem, but perhaps for a different reason.

I was running Anaconda, setup a virtual (conda) environment, installed Jupyter Lab.  Everything worked.

When, at some point later, I started Jupyter Lab in a different virtual environment (it might have been the base environment), the buttons disappeared.  Took a while to figure that out, of course.  But it was repeatable.  And switching to the correct virtual environment solved it.

-Marc

**Comment by MarshallCN** [comment]
Same issue here. Where I tried to use `pyLDAvis.display()`, the button icons disappeared. I guess the JS and CSS of pyLDAvis was conflicting with existing style.
![image](https://user-images.githubusercontent.com/16070638/89127692-8315cf80-d4e7-11ea-8b64-faac860cb3fe.png)
By export the graphs in a new page using `pyLDAvis.save_html(),` the icons are back. 
![image](https://user-images.githubusercontent.com/16070638/89127716-b35d6e00-d4e7-11ea-96b7-1f600989d731.png)
You can open the exported file and click "Trust HTML" to view the graph, and the icons are still there.
![image](https://user-images.githubusercontent.com/16070638/89127767-20710380-d4e8-11ea-8893-ec9538b1ddaf.png)

**Comment by cwhatley** [comment]
While certainly not ideal, you can get around this stylesheet issue by hitting JupyterLab through the notebook interface. The legacy notebook UI doesn't have SVG icons that would be be affected by pyLDAvis' style sheet.

Change "lab" to "tree" in the URL to get the legacy notebook UI and open your file from there.

**Comment by io-pan** [comment]
I agry with this:
> I'll add that those CSS lines are so overly broad that it's a wonder this hasn't caused problems up to this point. My guess is that narrowing that CSS down to where you actually want it applied would be a good first step.


By executing that line in the jupyter notebook fix most of my problems.

`from IPython.display import HTML  `
`css_str = '<style> \    `
`    .jp-Button path { fill: #616161;} \  `
`    text.terms { fill: #616161;} \  `
`</style>'  `
`display(HTML(css_str ))  `
`

**Comment by cheTesta** [comment]
> I agree with this:
> 
> > I'll add that those CSS lines are so overly broad that it's a wonder this hasn't caused problems up to this point. My guess is that narrowing that CSS down to where you actually want it applied would be a good first step.
> 
> Executing that code in the jupyter notebook fix most of my problems.
> 
> `from IPython.display import HTML `
> `css_str = '<style> \ `
> ` .jp-Button path { fill: #616161;} \ `
> ` text.terms { fill: #616161;} \ `
> `</style>' `
> `display(HTML(css_str )) `
> `
@io-pan nicely working but, w/ jupyter lab 3.0.7 there is an anomaly with the Interrupt kernel button

**Comment by io-pan** [comment]
> 
> This works for the top bar but still breaks the left hand nav bar

Yes I had to add a few css selectors for left-nav panel.

`
from IPython.display import HTML
css_str = '<style> \
    .jp-icon-warn0 path {fill: var(--jp-warn-color0);} \
    .bp3-button-text path {    fill: var(--jp-inverse-layout-color3);}\
    .jp-icon-brand0 path { fill: var(--jp-brand-color0);} \
    text.terms { fill: #616161;} \
</style>'
display(HTML(css_str))
`

**Comment by T0admomo** [comment]
Thank you so much for supplying this code! I'm wondering if this problem is also causing anyone to have issues with autocomplete function of the jupyter lab , or possibly , an alternative library to pyLDAvis that works well for visualizing LDA models?
