### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by suzana-ilic** [bmabey/pyLDAvis#163]
When importing 

import pyLDAvis
import pyLDAvis.gensim
import pyLDAvis.sklearn
pyLDAvis.enable_notebook()

I'm getting:

**DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping**

I can't find it though in the documentation - maybe I'm misunderstanding something, could anyone take look? Also, please close if irrelevant. Thanks!

**Comment by msusol** [comment]
Seems this was resolved by the merge. Please reevaluate the issue with v3.3.0 and create a new issue/PR for testing.
