### ISSUE TITLE
pyLDAvis worked once and hasn't worked since

### ISSUE THREAD

**Issue by jkaupanger** [bmabey/pyLDAvis#168]
I recently discovered the pyLDAvis library, and it's excellent. I implemented it the day I found it, and my visualizations were excellent.

And that's the only day it's worked. Every other time I try to open it in Jupyter, when I get to the pyLDAvis steps, I get a message that says that the kernel has died and will automatically restart. I've tried multiple virtual environments, I've uninstalled and reinstalled the libraries, I've uninstalled and reinstalled Jupyter, I've uninstalled and reinstalled Anaconda. I've tried in Jupyter, Pycharm, and from a terminal window. I cannot seem to get it working again.

**Comment by msusol** [comment]
Is this still an issue given latest release v3.2.2?
