### ISSUE TITLE
LDA visualisation in Jupyter notebook

### ISSUE THREAD

**Issue by jjgoodworth** [bmabey/pyLDAvis#176]
Any thoughts on this? Happy to paste the full question across if required

https://stackoverflow.com/questions/62823331/lda-visualisation-in-jupyter-notebook

**Comment by msusol** [comment]
Is this an issue with the latest release v3.2.2 ?

What are the conditions where you observed this? I couldn't understand from the screen shot what was overlapping

**Comment by msusol** [comment]
closing due to lack of response, consider obsolete w/ vs 3.3.1

**Comment by chschroeder** [comment]
Still occurs in 3.3.1 for me. The workaround in the linked stackoverflow post fixes the display.

The div with class "output_area" becomes larger than its parent div "output".
