### ISSUE TITLE
"Wrong" ldavis.js files delivered

### ISSUE THREAD

**Issue by jonaschn** [bmabey/pyLDAvis#188]
If one installs the current master with `pip install -e git://github.com/bmabey/pyLDAvis.git@master#egg=pyLDAvis`,
there exists following problem (and the visualization is not shown):

![image](https://user-images.githubusercontent.com/9538230/105725447-42908f00-5f29-11eb-8af2-d725d76dfb59.png)

This happens after #154 was merged.

**Comment by jonaschn** [comment]
The old ldavis.v1.0.0.js doesn't work with d3v5.
The updated [`ldavis.js`](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/js/ldavis.js) should be used instead.
I am not sure how to configure pyLDAvis to serve the updated `ldavis.js`.

**Comment by jonaschn** [comment]
As a temporary fix:
Run the previous master version cae66e8e221fa40c5ff1483aa292eeaced567b2e with 
`pip install -e git://github.com/bmabey/pyLDAvis.git@cae66e8e221fa40c5ff1483aa292eeaced567b2e#egg=pyLDAvis`

**Comment by msusol** [comment]
I can validate that this is a real issue. 

The main issue is that ldavis.js was updated but NOT ldavis.1.0.0.js. However, I can not get the DEV feature to work, or LOCAL mode even.

I actually have a commit I am working on to fix this issue, along with some other things I am finding (like lacking proper versioning). But I'm struggling to get this code to call up the right javascript file.

**Comment by jonaschn** [comment]
The correct js file is loaded only if the DEV mode is "enabled" which is the case if the version name contains `git`:
https://github.com/bmabey/pyLDAvis/blob/15cac9d39400d13f0070910151b0f22b2603e539/pyLDAvis/urls.py#L15

Simply change the version in __init__.py to `'git'` (or a string containing it) 
https://github.com/bmabey/pyLDAvis/blob/15cac9d39400d13f0070910151b0f22b2603e539/pyLDAvis/__init__.py#L42

**Comment by jonaschn** [comment]
I am not sure if updating `ldavis.1.0.0.js` could break backward compatibility :thinking: 
Maybe @bmabey or @dtemkin could help out here.

**Comment by bmabey** [comment]
@jonaschn will you see if [this commit](https://github.com/bmabey/pyLDAvis/commit/3f8e90079d2adc07662b1fe68e34380cc19294dc) fixes things for you?

**Comment by jonaschn** [comment]
Thanks @bmabey. This fixed the problem.
However, if I open the developer console in the browser and using jupyter notebook (v5.6.0) with Python 3.7 and IPython 6.5.0,
there occurs a mime/type issue:
![image](https://user-images.githubusercontent.com/9538230/107491091-0006bd80-6b8b-11eb-95c9-68ca5e14b08e.png)

But this is an unrelated issue and applies to the .css files as well.
Nevertheless, the visualization is rendered correctly :smile:

**Comment by jonaschn** [comment]
A similiar mime type issue is reported here #192
