### ISSUE TITLE
URL in saved html file giving 404 error "https://cdn.rawgit.com/bmabey/pyLDAvis/files/ldavis.v3.0.0.js"

### ISSUE THREAD

**Issue by bigbrihh** [bmabey/pyLDAvis#189]
when running pyLDAvis.show(), the generated html file tries to call this URL "https://cdn.rawgit.com/bmabey/pyLDAvis/files/ldavis.v3.0.0.js" which returns a 404 error code.

I found that an earlier version of the engine is available. "https://cdn.rawgit.com/bmabey/pyLDAvis/files/ldavis.v1.0.0.js"

**Comment by bmabey** [comment]
It looks like rawgit no longer is working so I updated the URLs.. could you try again with the latest version?

**Comment by bigbrihh** [comment]
your updates look good. Thanks for the quick fix.
