### ISSUE TITLE
pyLDAvis.show() in Jupyter Notebook returns FileNotFoundError

### ISSUE THREAD

**Issue by bigbrihh** [bmabey/pyLDAvis#190]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-30-a89f180b0543> in <module>
      1 LDAvis_prepared = pyLDAvis.gensim.prepare(lda_model, corpus, dict_lol)
----> 2 pyLDAvis.show(LDAvis_prepared)

/usr/local/lib/python3.9/site-packages/pyLDAvis/_display.py in show(data, ip, port, n_retries, local, open_browser, http_server, **kwargs)
    262                  open(urls.LDAVIS_LOCAL, 'r').read()],
    263                  '/LDAvis.css': ["text/css",
--> 264                                  open(urls.LDAVIS_CSS_URL, 'r').read()],
    265                  '/d3.js': ["text/javascript",
    266                             open(urls.D3_URL, 'r').read()]}

FileNotFoundError: [Errno 2] No such file or directory: 'https://cdn.rawgit.com/bmabey/pyLDAvis/files/ldavis.v1.0.0.css'

**Comment by mylesbartlett72** [comment]
I am having the same issue.  Using local=False solved it, but the viewing client requires an internet connection.  Am not sure why this is closed.

**Comment by msusol** [comment]
Please use the latest version which has these files versioned from cdn. When running local, it doesn't rely on cdn

**Comment by msusol** [comment]
Launching from jupyter notebook vs 3.4.0

```python
import pyLDAvis.gensim_models

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim_models.prepare(lda, corpus, dictionary)
pyLDAvis.show(vis, local=False) # local=False
```

avoids `FileNotFoundError: [Errno 2] No such file or directory: 'https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis@3.4.0/pyLDAvis/js/ldavis.v1.0.0.css'`

**Comment by WilliamLindskog** [comment]
Setting `pyLDAvis.show(vis, local=False)` seems to do the trick.
