### ISSUE TITLE
No labels in pyLDAvis output

### ISSUE THREAD

**Issue by nitinpunjabi** [bmabey/pyLDAvis#191]
I'm trying to visualize a Gensim LDA model in Colab and while the visualization is getting rendered, there are no word labels in the output. This is using pyLDAvis 3.1.0 and gensim 3.6.0. This is what the output looks like:

![image](https://user-images.githubusercontent.com/2571464/107386135-8f479e80-6ac1-11eb-84f6-f16805ae853b.png)

**Comment by msusol** [comment]
Yes, I was just coming to post this as well..

Also, when you click on the next topic, it does not DESELECT the previous one.

![Screen Shot 2021-02-09 at 3 58 14 PM](https://user-images.githubusercontent.com/2815031/107440117-5ecb2900-6af0-11eb-9783-c587be0eb8e9.png)

**Comment by VIJAYAYERUVA** [comment]
Thank you, @bmabey and team, for the great work **pyLDAvis**. 

Currently, I am also facing the similar kind of issues with the latest version.
Nothing is displayed when opening the '.html' file. I have used a similar code that I have used before.

**Comment by bmabey** [comment]
I just pushed a CSS fix that may be related so try again. Otherwise it is probably related to the D3 upgrade that was merged in. You could safely use a 2.x version if you don't need the latest D3 support. I don't have time to diagnose and fix any D3 related issues now. (sorry!)

**Comment by glaulom** [comment]
> I just pushed a CSS fix that may be related so try again. Otherwise it is probably related to the D3 upgrade that was merged in. You could safely use a 2.x version if you don't need the latest D3 support. I don't have time to diagnose and fix any D3 related issues now. (sorry!)

Just went back to 2.1.2 and it does work this way.

**Comment by msusol** [comment]
Be aware the versioning might be an issue back around 2.1.2 and others have suggested:

As a temporary fix:
Run the previous master version cae66e8 with
pip install -e git://github.com/bmabey/pyLDAvis.git@cae66e8e221fa40c5ff1483aa292eeaced567b2e#egg=pyLDAvis

**Comment by VIJAYAYERUVA** [comment]
Dear @bmabey and @msusol,

Thank you for the update. I will try these workarounds.

**Comment by nitinpunjabi** [comment]
Ok thanks @bmabey. Will revert.

**Comment by msusol** [comment]
The issue should not be closed. We still have the issue to resolve for vs
3.x
