### ISSUE TITLE
Change in behavior when running default code (local=False)

### ISSUE THREAD

**Issue by msusol** [bmabey/pyLDAvis#192]
When running the Gensim Newsgroup colab..

```python
vis_data = gensimvis.prepare(lda, corpus, dictionary)
pyLDAvis.display(vis_data)
```
the new version now reports in developer's console

`
Refused to apply style from 'https://raw.githubusercontent.com/bmabey/pyLDAvis/master/pyLDAvis/js/ldavis.v1.0.0.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
`

If I run local=True, there is no error. Not sure what the cause of this is or if it's relevant to latest version of code.

```python
vis_data = gensimvis.prepare(lda, corpus, dictionary)
pyLDAvis.display(vis_data, local=True)
```

**Comment by bmabey** [comment]
Okay, this should be resolved with #02a2e660. Reopen if that is not the case, thanks.
