### ISSUE TITLE
Y tick labels not displaying in jupyter notebook for term frequency

### ISSUE THREAD

**Issue by azespinoza** [bmabey/pyLDAvis#194]
Hello,

I am running into a visualization issue when running pyLDAvis.display() with any lda visualization from pyLDAvis.gensim.prepare(). 

Here is an example output from running this notebook http://nbviewer.ipython.org/github/bmabey/pyLDAvis/blob/master/notebooks/Gensim%20Newsgroup.ipynb

I have installed pyLDAvis 3.2.0 via pip. My OS is MacOS Big Sur v 11.1 and I am running this on python 3.8.5.

If I can provide any additional details to help please let me know!

![image](https://user-images.githubusercontent.com/37885553/107995659-8f4d1000-6f93-11eb-843c-2631a2b9a87b.png)

**Comment by dgonzo** [comment]
Even when saved to html y tick labels of css class `terms` are not showing. But it's not consistent. I'm including screenshots from the newsgroups dataset (missing tick labels) and an internal dataset (tick labels showing). Both generated using the same environment (macOS 10.15, python 3.8, pyLDAvis 3.2.0).
<img width="1480" alt="internal" src="https://user-images.githubusercontent.com/361559/108108349-c08a1680-704d-11eb-8519-0323bc4a0ebc.png">
<img width="1522" alt="newsgroups" src="https://user-images.githubusercontent.com/361559/108108355-c3850700-704d-11eb-9657-13dc54238351.png">

**Comment by msusol** [comment]
I am actually working on troubleshooting the latest d3.v5 upgrade.

**Comment by dgonzo** [comment]
@msusol If you can point me in the general direction in the codebase I'm happy to help. I love this visualization. I've benefited from using is for a long time and definitely owe the community for their efforts.

**Comment by msusol** [comment]
I appreciate the offer. I have it down to one point in the js where the labels are actually there, and then get removed. Its all on my laptop ready to continue in the morning

**Comment by simonwibberley** [comment]
I have downgraded to the last working version to workaround this for now:

`pip install --user pyLDAvis==2.1.2`

**Comment by msusol** [comment]
Update:
- The offending code that removes the Y-labels, is [chart.attr("class", "xaxis").call(xAxis);](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/js/ldavis.v3.0.0.js#L592)
- d3.scale.sqrt() was not upgraded d3.scaleSqrt().
- Revert the indexing changes i.e. (startIndex - 1).

I have the changes ready to push to Master/Pull request.

**Comment by msusol** [comment]
#198

**Comment by msusol** [comment]
@azespinoza Could you please try the latest version and verify the changes work for you too please?

**Comment by azespinoza** [comment]
Unfortunately the Y-labels are still missing for me in the latest version, but I do see them if I roll back to 2.1.2.

**Comment by msusol** [comment]
@bmabey Ben might need to update the CDN files because

https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis/pyLDAvis/js/ldavis.v3.0.0.js
does not match
https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/js/ldavis.v3.0.0.js

**Comment by msusol** [comment]
Look for new Pull Request to fix the browser cache issue

https://github.com/bmabey/pyLDAvis/pull/199

**Comment by msusol** [comment]
Ok, can you please give 3.2.2 a try?

**Comment by dgonzo** [comment]
@msusol confirmed. 3.2.2 fixes labels. Thank you!

**Comment by msusol** [comment]
You're welcome!

**Comment by azespinoza** [comment]
Apologies for the delay. It works for me as well now. Thank you so much @msusol. I'll close the issue.

**Comment by msusol** [comment]
You're welcome!
