### ISSUE TITLE
Saving visualization as png

### ISSUE THREAD

**Issue by hp0404** [bmabey/pyLDAvis#205]
Is it possible to save model visualization as `.png`? 

The code below allows me to save vis as `.html`, but I don't see anything in the docs about exporting to other formats

---

```
import pyLDAvis
import pyLDAvis.gensim

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda, corpus, dictionary)
pyLDAvis.save_html(vis, "vis.html") 
```

**Comment by msusol** [comment]
No, not a current feature as far as I know.

I found this useful: https://nytimes.github.io/svg-crowbar/

ref: https://stackoverflow.com/questions/41101424/downloading-the-image-produced-by-ldavis-library

and then: https://svgtopng.com/

![gensim-newsgroup---jupyter-notebook (3)](https://user-images.githubusercontent.com/2815031/116820361-e2197b00-ab31-11eb-9fb6-b84b47c2b604.png)
