### ISSUE TITLE
Frequency count missing in visualisation

### ISSUE THREAD

**Issue by ebbingcasa** [bmabey/pyLDAvis#206]
Hi everyone, hi Mark,

Thank you for pyLDAvis, it's so much fun working with it!

Here's my issue:

Whenever I create the visualisation of LDA, it doesn't show me the frequency count that's usually on top of the bar chart. Any idea why that is the case and how I can solve it? I already went through all the docs and papers but couldn't find anything. I'm visualising it in a Jupyter Notebook and exporting it as HTML leads to the same results. In Spyder, too, if I remember correctly but probably I should give that another try.

Thank you!

Best,
Peter

**Comment by msusol** [comment]
please see v3.3.1 which should provide what your missing

https://github.com/bmabey/pyLDAvis/pull/200

**Comment by ebbingcasa** [comment]
Seems like previous intent to upgrade didn't work out - works like a charm, thank you!
