### ISSUE TITLE
value error when "pyLDAvis.gensim.prepare(lda_model, corpus, id2word)" called

### ISSUE THREAD

**Issue by pwrsachin** [bmabey/pyLDAvis#208]
I am having this value error when I tried to visualize my LDA model on Jupiter notebook. I don't know how to fix this error. I am pasting the error below

ValueError                                Traceback (most recent call last)
<ipython-input-233-815ef7220b28> in <module>
      1 # Visualize the topics
      2 pyLDAvis.enable_notebook()
----> 3 vis = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
      4 #pyLDAvis.display(vis, template_type='notebook')
      5 #viz = pyLDAvis.display(vis, template_type='notebook')

~\anaconda3\lib\site-packages\pyLDAvis\gensim.py in prepare(topic_model, corpus, dictionary, doc_topic_dist, **kwargs)
    117     """
    118     opts = fp.merge(_extract_data(topic_model, corpus, dictionary, doc_topic_dist), kwargs)
--> 119     return vis_prepare(**opts)

~\anaconda3\lib\site-packages\pyLDAvis\_prepare.py in prepare(topic_term_dists, doc_topic_dists, doc_lengths, vocab, term_frequency, R, lambda_step, mds, n_jobs, plot_opts, sort_topics, start_index)
    416     def to_json(self):
    417        return json.dumps(self.to_dict(), cls=NumPyEncoder)

~\anaconda3\lib\site-packages\pandas\core\ops\__init__.py in f(self, other, axis, level, fill_value)

~\anaconda3\lib\site-packages\pandas\core\ops\__init__.py in _combine_series_frame(self, other, func, fill_value, axis, level)

~\anaconda3\lib\site-packages\pandas\core\frame.py in _combine_match_index(self, other, func)
   5315         DataFrame.drop_duplicates : Remove duplicate values from DataFrame.
   5316 
-> 5317         Examples
   5318         --------
   5319         Consider dataset containing ramen rating.

~\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py in na_op(x, y)
    119     """
    120     Return the result of evaluating op on the passed in values.
--> 121 
    122     If native types are not compatible, try coercion to object dtype.
    123 

~\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py in na_arithmetic_op(left, right, op, str_rep)
    147             #  will handle complex numbers incorrectly, see GH#32047
    148             raise
--> 149         result = _masked_arith_op(left, right, op)
    150 
    151     if is_cmp and (is_scalar(result) or result is NotImplemented):

~\anaconda3\lib\site-packages\pandas\core\computation\expressions.py in evaluate(op, a, b, use_numexpr)
    230     op_str = _op_str_mapping[op]
    231     if op_str is not None:
--> 232         use_numexpr = use_numexpr and _bool_arith_check(op_str, a, b)
    233         if use_numexpr:
    234             # error: "None" not callable

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by saadiga** [comment]
Facing same issues with 

(base) macs-mbp:~ mac$ pip show pyLDAvis
Name: pyLDAvis
Version: 3.3.1

code
LDAvis_prepared = pyLDAvis.gensim_models.prepare(lda_model, corpus, id2word)


error stack trace


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-48-b193b588b556> in <module>
      8 # # if you want to execute visualization prep yourself
      9 
---> 10 LDAvis_prepared = pyLDAvis.gensim_models.prepare(lda_model, corpus, id2word)
     11 #with open(LDAvis_data_filepath, 'wb') as f:
     12 #    pickle.dump(LDAvis_prepared, f)

~/opt/anaconda3/lib/python3.7/site-packages/pyLDAvis/gensim_models.py in prepare(topic_model, corpus, dictionary, doc_topic_dist, **kwargs)
    121     """
    122     opts = fp.merge(_extract_data(topic_model, corpus, dictionary, doc_topic_dist), kwargs)
--> 123     return pyLDAvis.prepare(**opts)

~/opt/anaconda3/lib/python3.7/site-packages/pyLDAvis/_prepare.py in prepare(topic_term_dists, doc_topic_dists, doc_lengths, vocab, term_frequency, R, lambda_step, mds, n_jobs, plot_opts, sort_topics, start_index)
    416     R = min(R, len(vocab))
    417 
--> 418     topic_freq = doc_topic_dists.mul(doc_lengths, axis="index").sum()
    419     # topic_freq       = np.dot(doc_topic_dists.T, doc_lengths)
    420     if (sort_topics):

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/ops/__init__.py in f(self, other, axis, level, fill_value)

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/ops/__init__.py in _combine_series_frame(self, other, func, fill_value, axis, level)

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in _combine_match_index(self, other, func)
   5315         DataFrame.drop_duplicates : Remove duplicate values from DataFrame.
   5316 
-> 5317         Examples
   5318         --------
   5319         Consider dataset containing ramen rating.

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py in na_op(x, y)
    119     """
    120     Return the result of evaluating op on the passed in values.
--> 121 
    122     If native types are not compatible, try coercion to object dtype.
    123 

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py in na_arithmetic_op(left, right, op, str_rep)
    147             #  will handle complex numbers incorrectly, see GH#32047
    148             raise
--> 149         result = _masked_arith_op(left, right, op)
    150 
    151     if is_cmp and (is_scalar(result) or result is NotImplemented):

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/computation/expressions.py in evaluate(op, a, b, use_numexpr)
    230     op_str = _op_str_mapping[op]
    231     if op_str is not None:
--> **232         use_numexpr = use_numexpr and _bool_arith_check(op_str, a, b)**
    233         if use_numexpr:
    234             # error: "None" not callable

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by saadiga** [comment]
looks like a classical error:
https://stackoverflow.com/questions/10062954/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous

I wonder if it's working for other users

**Comment by jshhrrsn** [comment]
I'm also faced with this issue, have anyone been able to resolve?  

pyLDAvis==3.3.1
pandas==1.2.3

Note I'm using pandas 1.2.3 as this is an explicit requirement of gensim: 

https://github.com/RaRe-Technologies/gensim/blob/a93067d2ea78916cb587552ba0fd22727c4b40ab/requirements_docs.txt#L7

**Comment by msusol** [comment]
pyLDAvis==3.4.0 will not support python3.7, so try again after the new release is available.

I feel like that was address though.
