### ISSUE TITLE
pyLDAvis  support for manual topic tagging not in vs 3.3.1 release ?

### ISSUE THREAD

**Issue by lucawagner1510** [bmabey/pyLDAvis#211]
Hi,
I'm searching for support for manual topic tagging and I saw:  https://github.com/bmabey/pyLDAvis/pull/90

but now I don't see this support in 3.3.1 release:  @msusol could you help me to solve this issue?

Many Thanks
Luca

**Comment by msusol** [comment]
That feature request was closed after lack of response from the author to make the upgrades after we converted from `d3.v3.js` to `d3.v5.js`. So that feature has never been merged to trunk.

**Comment by lucawagner1510** [comment]
Ok,
thanks for the clarification.
L
