### ISSUE TITLE
Gensim has lots of bugs

### ISSUE THREAD

**Issue by lakchchayam** [bmabey/pyLDAvis#214]
![image](https://user-images.githubusercontent.com/49754403/127113021-edc48844-137a-4733-915a-213fce44d863.png)

**Comment by msusol** [comment]
Please use the latest version 3.3.1 (I do no see any information about what version you are using.) 
Where are you getting this code example from?

```
import pyLDAvis.gensim (as gensimvis)
```

is now

```
import pyLDAvis.gensim_models (as gensimvis)
```

See https://github.com/bmabey/pyLDAvis/commit/dfdf93070ff2f70ca227068e1e6f3525224d8816

**Comment by lakchchayam** [comment]
worked!
