### ISSUE TITLE
Program stopped due to OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by laicr-sufe** [bmabey/pyLDAvis#217]
When I use the pyLDAvis library
```python
vis = pyLDAvis.gensim_models.prepare(lda, corpus, dictionary)
pyLDAvis.show(vis)
```
I get the following error

      File "C:\ProgramData\Anaconda3\lib\site-packages\pyLDAvis\_display.py", line 262, in show
        '/LDAvis.css': ["text/css", open(urls.LDAVIS_CSS_URL, 'r').read()],
    OSError: [Errno 22] Invalid argument: 'https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis@3.3.1/pyLDAvis/js/ldavis.v1.0.0.css'
After this I went to the _display.py file and looked at the source code of the "show" function, and I think there is something wrong with lines 261 to 263 of the code in the file
```python
files = {'/LDAvis.js': ["text/javascript", open(urls.LDAVIS_LOCAL, 'r').read()],
         '/LDAvis.css': ["text/css", open(urls.LDAVIS_CSS_URL, 'r').read()],
         '/d3.js': ["text/javascript", open(urls.D3_URL, 'r').read()]}
```
The "open" function may not seem to take url as an argument, so I import the following library
```python
import requests
from bs4 import *
```
and rewrite the function to the following form
```python
files = {'/LDAvis.js': ["text/javascript", open(urls.LDAVIS_LOCAL, 'r').read()],
         '/LDAvis.css': ["text/css", BeautifulSoup(requests.get(url=urls.LDAVIS_CSS_URL).text, 'lxml').select('p')[0].get_text()],
         '/d3.js': ["text/javascript", BeautifulSoup(requests.get(url=urls.D3_URL).text, 'lxml').select('p')[0].get_text()]}
```
My project finally works.
It's a bug? or I make something wrong when I install the pyLDAvis?

**Comment by dennn93** [comment]
[laicr-sufe](https://github.com/laicr-sufe),excellent, everything works!

**Comment by msusol** [comment]
not sure why it works in l#263, but not in l#264-265 for you. will close this for now, please try vs 3.4.0 and report back (but the code didn't change around this issues)

**Comment by giolm1** [comment]
I also get the same error message.

**Comment by wachoo** [comment]
from pyLDAvis import gensim_models as gensim_vis

vis_data = gensim_vis.prepare(lda_model, corpus, text_dict)
print(vis_data)
pyLDAvis.display(vis_data)
pyLDAvis.save_html(vis_data, os.path.join(script_dir, 'output', 'pics', f'{TITLE}-topics-{YEAR}.html'))
pyLDAvis.show(vis_data, local=False)
