### ISSUE TITLE
pyLDAvis doesn't have dependencies listed on PyPI

### ISSUE THREAD

**Issue by OliRafa** [bmabey/pyLDAvis#220]
The library doesn't have its dependencies listed on PyPI.
This is a problem because it obligates dependency management tools (like Poetry) to download the whole package just to check its dependencies and versions in order to resolve which dependency versions it'll install.

This is a big problem for tools like Poetry to run in a reasonable time, and starting listing this package dependencies would help to solve it. More on this can be found on https://github.com/python-poetry/poetry/issues/2094 .

**Comment by msusol** [comment]
Let's re-evaluate in vs 3.4.0
