### ISSUE TITLE
pyLDAvis | Getting error while collecting sklearn

### ISSUE THREAD

**Issue by sharmaapeksha960** [bmabey/pyLDAvis#225]
Hi

I got a problem where I tried to install pyLDAvis in an environment in Anaconda prompt.

Inorder to install I used _pip install pyldavis._ 

On execution it stopped with an error saying it was not able to install requirement for sklearn. So I installed scikit-learn first using _pip install scikit-learn_ and then tried installing pyldavis again. but still it didnt work. Is there anything that I am missing out here?

This was the error that I got when I first tried to install pyldavis:
_Collecting sklearn
  ERROR: HTTP error 403 while getting https://.........)_

**Comment by sharmaapeksha960** [comment]
Anyone faced this issue or a possible solution to resolve this?

**Comment by msusol** [comment]
Make sure you have these packages installed and at the versions listed:
https://github.com/bmabey/pyLDAvis/blob/master/requirements.txt

Also, make sure to use `pip3 install pyldavis` in the event you still have python2.x installed: `pip3 --version` should help you determine if you are in python3.8+

**Comment by msusol** [comment]
> was not able to install requirement for sklearn. 

removed from requirements in in vs 3.4.0
