### ISSUE TITLE
Sklearn Count Vector 

### ISSUE THREAD

**Issue by Machin3M0d3** [bmabey/pyLDAvis#228]
sklearn.feature_extraction.text.CountVectorizer.get_feature_names() is DEPRECATED.

The method is now sklearn.feature_extraction.text.CountVectorizer.get_feature_names_out() .

This is giving me issues when trying to use the sklearn count vector in preparing the pyLDAvis.

**Comment by msusol** [comment]
https://github.com/bmabey/pyLDAvis/pull/235
