### ISSUE TITLE
Add "Documents" link to topic panel

### ISSUE THREAD

**Issue by gitgash** [bmabey/pyLDAvis#23]
On the topic panel add link "Documents"
Clicking this link bring up documents list sorted by relevance.

**Comment by bmabey** [comment]
Yes, I'd like to see something like this as well. The challenge is to keep the data sent to the browser as small as possible. This is something I'm thinking about doing though.

**Comment by bmabey** [comment]
After thinking about this a bit more I don't think `pyLDAvis` should ever be a corpus explorer. Such a tool would be useful but I think it would be best to create a new project since part of `pyLDAvis`'s goal is to mirror the R library.
