### ISSUE TITLE
'TfidfVectorizer' object has no attribute 'get_feature_names'

### ISSUE THREAD

**Issue by mahdi-1992** [bmabey/pyLDAvis#244]
I installed pyldavis in colab but when i run this code
" pyLDAvis.sklearn.prepare(nmf_tfidf, tfidf, vectorizer)"
this error is show:"'TfidfVectorizer' object has no attribute 'get_feature_names'"

where is my code trouble and how to solve it

**Comment by msusol** [comment]
https://github.com/bmabey/pyLDAvis/issues/245
