### ISSUE TITLE
How to use pyinstaller package pyLDAvis?

### ISSUE THREAD

**Issue by zc1018x** [bmabey/pyLDAvis#246]
I used pyinstaller package into software, a lot of Windows pop up when I run it?Does anyone know how to solve it?thanks

**Comment by argzxf** [comment]
`import multiprocessing
from joblib import parallel_backend

multiprocessing.freeze_support()
parallel_backend("threading")`

**Comment by zc1018x** [comment]
Thank you for your answer。
