### ISSUE TITLE
pyLDAvis.lda_model.prepare(), I get an error "BrokenProcessPool"

### ISSUE THREAD

**Issue by msusol** [bmabey/pyLDAvis#249]
Hello,

When I use pyLDAvis.lda_model.prepare(), I get an error "BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable." That function worked a couple of weeks ago for the same code and data. Could you please help?

_Originally posted by @ulneva in https://github.com/bmabey/pyLDAvis/issues/245#issuecomment-1520570191_

**Comment by msusol** [comment]
@ulneva Can you please provide the actual code to reproduce the issue? Also what version of python, pyLDAvis, etc.

**Comment by Rikesh-Patel** [comment]
Does this possibly stem from "ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'"

The following code was working yesterday, but today it provides me the same error stated above:
lda_model = gensim.models.ldamodel.LdaModel(corpus=corpus2, id2word=id2word, num_topics=7, random_state=9, per_word_topics = True, alpha="auto")
pyLDAvis.gensim_models.prepare(lda_model, corpus2, id2word)

**Comment by msusol** [comment]
Reinstall pyLDAvis with vs 3.4.1.. so you get the proper requirements installed.

**Comment by Rikesh-Patel** [comment]
Thank you. The error was fixed for me after downgrading my pandas version:
pip install pandas==1.5.1

**Comment by ulneva** [comment]
Thank you fo looking into this. I was running the code in the attached file called topic_modeling_issue (that script calls the other file called text_normalization_function so I am attaching both) on Google Colab. They used to run on Google Colab just fine. Thanks, again! 

[Text_Normalization_Function.ipynb.zip](https://github.com/bmabey/pyLDAvis/files/11315322/Text_Normalization_Function.ipynb.zip)
[Topic_Modeling_Issue.ipynb.zip](https://github.com/bmabey/pyLDAvis/files/11315324/Topic_Modeling_Issue.ipynb.zip)

**Comment by daveleee** [comment]
For those who have similar issues, in my case the pyLDAvis version was 3.4.1 and it worked with pandas 1.5.1
