### ISSUE TITLE
ModuleNotFoundError: No module named 'pyLDAvis.sklearn'

### ISSUE THREAD

**Issue by AsmaZbt** [bmabey/pyLDAvis#251]
hello,

I have installed pyLDAvis with pip as mentioned in the documentation. 
I successfully imported  
import pyLDAvis
import pyLDAvis.gensim

however when I would like to importe the pyLDAvis.sklearn I got this error: 

ModuleNotFoundError: No module named 'pyLDAvis.sklearn'

pyLDAvis.__version__
'3.4.0'

can you help me please?

**Comment by msusol** [comment]
https://github.com/bmabey/pyLDAvis/issues/245

**Comment by msusol** [comment]
per #245 

**pyLDAvis v 3.4.0 no longer has the file `sklearn.py` in the pip package.**

Replace any logic involving
```python
import pyLDAvis.sklearn
...
pyLDAvis.sklearn.prepare
```
with

```python
import pyLDAvis.lda_model
...
pyLDAvis.lda_model.prepare
```

**Comment by magnolia-gon** [comment]
Thanks a lot! I tried `lda_model` and succeeded
