### ISSUE TITLE
Why is there no data in the example notebooks?

### ISSUE THREAD

**Issue by ooker777** [bmabey/pyLDAvis#252]
The files in [notebooks/data](https://github.com/bmabey/pyLDAvis/tree/master/notebooks/data) are all empty. Why is that?

**Comment by msusol** [comment]
The files are symbolic links to the test directory. Just access them directly.

Ex: https://github.com/bmabey/pyLDAvis/blob/master/tests/data/movie_reviews_input.json

**Comment by ooker777** [comment]
why do you put them in multiple places?

**Comment by msusol** [comment]
They were in one test directory and symbolically linked from the other. I'm not the original author, its just how it was done
