### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis@3.4.0/pyLDAvis/js/ldavis.v1.0.0.css'

### ISSUE THREAD

**Issue by lxopencv** [bmabey/pyLDAvis#254]
in pyLDAvis 3.4.1
File "/home/l/1/venv/lib/python3.10/site-packages/pyLDAvis/_display.py", line 262, in show
    '/LDAvis.css': ["text/css", open(urls.LDAVIS_CSS_URL, 'r').read()],
FileNotFoundError: [Errno 2] No such file or directory: 'https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis@3.4.0/pyLDAvis/js/ldavis.v1.0.0.css'

**Comment by msusol** [comment]
The [file does exist](https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis@3.4.0/pyLDAvis/js/ldavis.v1.0.0.css), not sure why you got this error. 3.4.0 = 3.4.1 at least. But it should be 3.4.1 which I will fix in master, but won't be able to fix until pushing out 3.4.2

https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/__init__.py#L42
