### ISSUE TITLE
TypeError: drop() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Lynn2828** [bmabey/pyLDAvis#259]
# 使用pyLDAvis進行視覺化
import pyLDAvis.gensim as gensimvis
import pyLDAvis
pyLDAvis.enable_notebook()

vis = gensimvis.prepare(lda_model, corpus, dictionary_LDA)
# 保存視覺化結果為HTML文件
pyLDAvis.save_html(vis, 'cn_lda_visualization.html')

print("LDA visualization saved as lda_visualization.html")

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-63-cd996698b4e6> in <module>
      4 pyLDAvis.enable_notebook()
      5 
----> 6 vis = gensimvis.prepare(lda_model, corpus, dictionary_LDA)
      7 # 保存視覺化結果為HTML文件
      8 pyLDAvis.save_html(vis, 'cn_lda_visualization.html')

~/opt/anaconda3/lib/python3.8/site-packages/pyLDAvis/gensim.py in prepare(topic_model, corpus, dictionary, doc_topic_dist, **kwargs)
    121     """
    122     opts = fp.merge(_extract_data(topic_model, corpus, dictionary, doc_topic_dist), kwargs)
--> 123     return vis_prepare(**opts)

~/opt/anaconda3/lib/python3.8/site-packages/pyLDAvis/_prepare.py in prepare(topic_term_dists, doc_topic_dists, doc_lengths, vocab, term_frequency, R, lambda_step, mds, n_jobs, plot_opts, sort_topics, start_index)
    430     term_frequency = np.sum(term_topic_freq, axis=0)
    431 
--> 432     topic_info = _topic_info(topic_term_dists, topic_proportion,
    433                              term_frequency, term_topic_freq, vocab, lambda_step, R,
    434                              n_jobs, start_index)

~/opt/anaconda3/lib/python3.8/site-packages/pyLDAvis/_prepare.py in _topic_info(topic_term_dists, topic_proportion, term_frequency, term_topic_freq, vocab, lambda_step, R, n_jobs, start_index)
    241         'Total': term_frequency,
    242         'Category': 'Default'})
--> 243     default_term_info = default_term_info.sort_values(
    244         by='saliency', ascending=False).head(R).drop('saliency', 1)
    245     # Rounding Freq and Total to integer values to match LDAvis code:

TypeError: drop() takes from 1 to 2 positional arguments but 3 were given

**Comment by msusol** [comment]
Following the notebook for vs 3.4.1, the correct code to use is given as

```python
import pyLDAvis.gensim_models as gensimvis # gensim -> gensim_models
import pyLDAvis

vis_data = gensimvis.prepare(lda, corpus, dictionary)
pyLDAvis.display(vis_data)
```

**Comment by msusol** [comment]
Correcting the code for v 3.4.1: `pyLDAvis.gensim` -> `pyLDAvis.gensim_models`

```python
import pickle
from gensim import models
#import pyLDAvis.gensim
import pyLDAvis.gensim_models as gensimvis

id2word = pickle.load(open('../data/id2word.pkl','rb'))
cv_vecs = pickle.load(open('../data/cv_vecs.pkl','rb'))
cv_corpus = pickle.load(open('../data/cv_corpus.pkl','rb'))
lda =  models.LdaModel.load('../data/gensim_lda.model')

#viz = pyLDAvis.gensim.prepare(topic_model=lda, corpus=cv_corpus, dictionary=id2word, mds='mmds')
viz = gensimvis.prepare(topic_model=lda, corpus=cv_corpus, dictionary=id2word, mds='mmds')
```

Do you still get the same error?
