### ISSUE TITLE
Feature request: build for Conda

### ISSUE THREAD

**Issue by tdhopper** [bmabey/pyLDAvis#28]
Ben — Could you consider releasing pyLDAvis on Anaconda.org?

**Comment by bmabey** [comment]
Okay. I have pushed some to my personal channel using the skeketon command via pip. I agree that an actual conda release would be useful, especially for Window users. I've never automated a conda build before but I'll look into it.

**Comment by tdhopper** [comment]
It can be a pain: http://stiglerdiet.com/blog/2015/Aug/06/releasing-to-anaconda.org-via-travis-ci/
