### ISSUE TITLE
Error preparing gensim model

### ISSUE THREAD

**Issue by craigpfeifer** [bmabey/pyLDAvis#31]
Using python 3.4, trying to prepare a gensim-generated LDA model gives the following stack trace:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-303e7d5a5bc5> in <module>()
      1 import pyLDAvis.gensim
      2 
----> 3 pyLDAvis.gensim.prepare(lda, corpus, dictionary)

/usr/local/lib/python3.4/site-packages/pyLDAvis/gensim.py in prepare(topic_model, corpus, dictionary, **kargs)
     64     http://nbviewer.ipython.org/github/bmabey/pyLDAvis/blob/master/notebooks/Gensim%20Newsgroup.ipynb
     65     """
---> 66     opts = fp.merge(_extract_data(topic_model, corpus, dictionary), kargs)
     67     return vis_prepare(**opts)

/usr/local/lib/python3.4/site-packages/pyLDAvis/gensim.py in _extract_data(topic_model, corpus, dictionary)
     30 
     31    topics = topic_model.show_topics(formatted=False, num_words=len(vocab), num_topics=topic_model.num_topics)
---> 32    topics_df = pd.DataFrame([dict((y,x) for x, y in tuples) for tuples in topics])[vocab]
     33    topic_term_dists = topics_df.values
     34 

/usr/local/lib/python3.4/site-packages/pandas/core/frame.py in __getitem__(self, key)
   1912             return self._getitem_multilevel(key)
   1913         else:
-> 1914             return self._getitem_column(key)
   1915 
   1916     def _getitem_column(self, key):

/usr/local/lib/python3.4/site-packages/pandas/core/frame.py in _getitem_column(self, key)
   1919         # get column
   1920         if self.columns.is_unique:
-> 1921             return self._get_item_cache(key)
   1922 
   1923         # duplicate columns & possible reduce dimensionaility

/usr/local/lib/python3.4/site-packages/pandas/core/generic.py in _get_item_cache(self, item)
   1086         """ return the cached item, item represents a label indexer """
   1087         cache = self._item_cache
-> 1088         res = cache.get(item)
   1089         if res is None:
   1090             values = self._data.get(item)

TypeError: unhashable type: 'dict_keys'

**Comment by bmabey** [comment]
I believe this is fixed in master but has not yet made it into a release.

**Comment by craigpfeifer** [comment]
Okay! When is a release slated?

**Comment by Grinshpun** [comment]
Wow, what I timing. I was just about to start crying with the same issue/problem. bmabey are there file(s) we can get form the master, or do we wait for the release? Can you kindly verify?

**Comment by bmabey** [comment]
@craigpfeifer @Grinshpun I just released `v1.3.1`. Please try it out to see if it resolves your issues.

**Comment by craigpfeifer** [comment]
Fixed! Thank you!
