### ISSUE TITLE
Python 3.4 deprecation

### ISSUE THREAD

**Issue by craigpfeifer** [bmabey/pyLDAvis#35]
When I use PyLDAVis w/python 3.4, I get the following warnings. The package works perfectly, just for future reference.

/usr/local/lib/python3.4/site-packages/pyLDAvis/_prepare.py:283: FutureWarning: order is deprecated, use sort_values(...)
  topic_proportion = (topic_freq / topic_freq.sum()).order(ascending=False)
/usr/local/lib/python3.4/site-packages/pyLDAvis/_prepare.py:154: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  sort('saliency', ascending=False). \
/usr/local/lib/python3.4/site-packages/pyLDAvis/_prepare.py:203: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  return token_table.sort(['Term', 'Topic'])
/usr/local/lib/python3.4/site-packages/pyLDAvis/_prepare.py:132: FutureWarning: order is deprecated, use sort_values(...)
  return relevance.T.apply(lambda s: s.order(ascending=False).index).head(R)

**Comment by bmabey** [comment]
This will be resolved once #32 has been merged in.
