### ISSUE TITLE
Gensim Prepare

### ISSUE THREAD

**Issue by methodds** [bmabey/pyLDAvis#38]
Preparing a gensim lda model does not work for me (Linux, Python 3.4) because of the following error:
``
pyLDAvis.gensim.prepare(lda, corpus, dictionary)

TypeError                                 Traceback (most recent call last)
<ipython-input-184-33dcf963aeba> in <module>()
----> 1 pyLDAvis.gensim.prepare(lda, corpus, dictionary)

/home/methodds/anaconda3/lib/python3.4/site-packages/pyLDAvis/gensim.py in prepare(topic_model, corpus, dictionary, **kargs)
     64     http://nbviewer.ipython.org/github/bmabey/pyLDAvis/blob/master/notebooks/Gensim%20Newsgroup.ipynb
     65     """
---> 66     opts = fp.merge(_extract_data(topic_model, corpus, dictionary), kargs)
     67     return vis_prepare(**opts)

/home/methodds/anaconda3/lib/python3.4/site-packages/pyLDAvis/gensim.py in _extract_data(topic_model, corpus, dictionary)
     30 
     31    topics = topic_model.show_topics(formatted=False, num_words=len(vocab), num_topics=topic_model.num_topics)
---> 32    topics_df = pd.DataFrame([dict((y,x) for x, y in tuples) for tuples in topics])[vocab]
     33    topic_term_dists = topics_df.values
     34 

/home/methodds/anaconda3/lib/python3.4/site-packages/pyLDAvis/gensim.py in <listcomp>(.0)
     30 
     31    topics = topic_model.show_topics(formatted=False, num_words=len(vocab), num_topics=topic_model.num_topics)
---> 32    topics_df = pd.DataFrame([dict((y,x) for x, y in tuples) for tuples in topics])[vocab]
     33    topic_term_dists = topics_df.values
     34 

/home/methodds/anaconda3/lib/python3.4/site-packages/pyLDAvis/gensim.py in <genexpr>(.0)
     30 
     31    topics = topic_model.show_topics(formatted=False, num_words=len(vocab), num_topics=topic_model.num_topics)
---> 32    topics_df = pd.DataFrame([dict((y,x) for x, y in tuples) for tuples in topics])[vocab]
     33    topic_term_dists = topics_df.values
     34 

TypeError: 'int' object is not iterable
``
Any idea what is going on here?

**Comment by bmabey** [comment]
Are you on the latest version of pyldavis?

-Ben

**Comment by methodds** [comment]
Yes, I am using pyLDAvis 1.3.1

**Comment by mattilyra** [comment]
@methodds can you try pulling the `gensim_speed` branch from my fork. I think this is a problem with `pandas` not `funcy`. The error comes from line 32 which has an unnecessary conversion to a dataframe, which is undone on the next line. The `gensim_speed` branch gets rid of that call and should fix the issue. It hasn't been merged into master yet though, so it's not guaranteed to be stable - I've not had any problems with it though.

**Comment by Grinshpun** [comment]
Mr. Mabey

I second that motion. I have a 1,3.1 installed today. I ran a simple script that loads the model and call prepare, and got the same error. Win 10 Python 3.4.3.6 I am attaching a screen shot with execution.

I will try to see see if I can get the Mr. Illyra's branch but in the mean time this is not working.

Thanks
Vadim
![pyldavis_err](https://cloud.githubusercontent.com/assets/15304277/11017396/a3787c9e-856b-11e5-8ba7-1900d8a579b0.png)

**Comment by methodds** [comment]
@mattilyra You were right, your ``gensim_speed`` branch works flawlessly. Thank you! :)

**Comment by Grinshpun** [comment]
@mattilyra your  code changes appear have resolved that particular issue

**Comment by ibarria0** [comment]
@methodds im getting the same error...
@mattilyra I cant find your branch

**Comment by mattilyra** [comment]
@ibarria0 You need to do `git remote add mattilyra https://github.com/mattilyra/pyLDAvis.git` and then `git fetch mattilyra` to get the branch to show up on your local machine. You can then do `git checkout gensim_speed`.

**Comment by ibarria0** [comment]
@mattilyra It works

**Comment by mattilyra** [comment]
@ibarria0 the branch or the git?

**Comment by ibarria0** [comment]
@mattilyra the branch

**Comment by Grinshpun** [comment]
@ibarria0 Not sure if it's ok to barge-in, but being relatively new to the whole scene, I simply made the backup copies of the two original python files, and then replaced the content of the two files changed in Mr. Lyra's code (not the setup.py) with content from the Raw view of the changes. All took less than 10 min and worked fine.

**Comment by bmabey** [comment]
@mattlyra I'd like to merge the branch in and release it. Did you want to do anything else on it before I do?

**Comment by mattilyra** [comment]
As far as I am concerned the branch is fine. I  checked that the resulting model visualisation is the same as from the old code - so the vocabulary order should be correct.

**Comment by ibarria0** [comment]
@Grinshpun that is exactly what I did :)

**Comment by bmabey** [comment]
I've merged in @mattilyra's changes and have released `v1.3.2`. If someone could upgrade to the latest and report back I'd appreciate it.
