### ISSUE TITLE
Python Visualization Fails to scroll - the nagging continues

### ISSUE THREAD

**Issue by Grinshpun** [bmabey/pyLDAvis#40]
Mr. Mabbey 

Great thanks for your last answer - I was able (took me less than a year) to open a notebook and run the code. The code ran, the graphic appeared, but I can only see the top part of it and toggling scrolling of the output does not help. I realize the issue here is not so much the code as my ignorance, but any help/advice is greately appreciated.

Thanks
Vadim
![noscroll](https://cloud.githubusercontent.com/assets/15304277/11020928/416de1ea-85fe-11e5-9797-fc53a9a10bbc.png)

**Comment by bmabey** [comment]
I never tested it with Internet Explorer. Try a different browser like Chrome.

**Comment by Grinshpun** [comment]
pronlem is - when do the ipython notebook comman ie comes up. will reset the default browser, try with chrome and report back to you. FYI IE v11

**Comment by Grinshpun** [comment]
Google Chrome v46.0 works fine. do you think it's the issue with pyLDAvis or ipython and should repost it to one of their branches/blogs?

**Comment by bmabey** [comment]
The problem is probably how IE is rendering the CSS found in IPython. IE may not even be supported by IPython.
