### ISSUE TITLE
Gensim breaking change to show_topics in 0.12.3

### ISSUE THREAD

**Issue by craigpfeifer** [bmabey/pyLDAvis#41]
FYI : Gensim 0.12.3 show_topics changes:

All models with the `show_topics` method should return a list of
    `(topic_number, topic)` tuples, where `topic` is a list of
    `(word, probability)` tuples.

via changelog (https://github.com/piskvorky/gensim/blob/develop/CHANGELOG.txt)

**Comment by bmabey** [comment]
Thanks for the heads up. Luckily I just merged in a PR that takes a different (and faster) approach: https://github.com/bmabey/pyLDAvis/commit/420cbe0c3d7d5e149f11f8bf8ec0a3f790d00df7
