### ISSUE TITLE
support for gensim hdp

### ISSUE THREAD

**Issue by methodds** [bmabey/pyLDAvis#47]
Is it possible to also support hdp models from gensim? as far as I understand it the underlying voodoo as well as the output are very similar, but you don't have to choose the number of topics for hdp:
https://radimrehurek.com/gensim/models/hdpmodel.html

**Comment by bmabey** [comment]
I have not had good luck with Gensim's HDP model in general. A co-worker of mine got it's HDP to work with pyLDAvis but it wasn't as straight forward as we thought it would be and it never looked like it produced useful miles. YMMV, but I won't be adding support.

If you want to do HDP with pyLDAvis then I suggest you look at the [datamicroscopes](https://github.com/datamicroscopes/lda) library. It ships with a pyLDAvis function. See it in action in this [notebook](https://datamicroscopes.github.io/hdp.html). It uses gibbs sampling so it is slower than the gensim version but I liked the resulting models much better.
