### ISSUE TITLE
port over new bar calculation logic from R LDAvis

### ISSUE THREAD

**Issue by bmabey** [bmabey/pyLDAvis#51]
https://github.com/cpsievert/LDAvis/pull/41

**Comment by bmabey** [comment]
@bobflagg any updates on this patch?

**Comment by bobflagg** [comment]
@ *bmabey <https://github.com/bmabey>I should be able to get this done 
soon - hopefully this weekend. *

**Comment by bmabey** [comment]
fixed by #54.
