### ISSUE TITLE
Very small visualization

### ISSUE THREAD

**Issue by kevinbsc** [bmabey/pyLDAvis#56]
pyLDAvis.display(movies_vis_data) generates LDA visualization, but it shows top part of the visualization. 
![pyldavis](https://cloud.githubusercontent.com/assets/3991133/13377000/450a3914-dd8f-11e5-93ba-34ad7574eac6.GIF)

**Comment by bmabey** [comment]
Maybe your IPython cell is collapsed? (Click to the left of the viz in the cell margin)

Without steps to reproduce this I won't be able to help.

**Comment by kevinbsc** [comment]
Thanks for your reply. I just found that the issue exists with Internet Explorer. Everything works fine with Firefox
