### ISSUE TITLE
Error installing pyLDAvis

### ISSUE THREAD

**Issue by aaajjj333** [bmabey/pyLDAvis#57]
When I use pip to install this package it shows error with one of the dependencies (scikit-bio)

After a long search it turns out that scikit-bio is not compatible with windows yet. Are you aware of this problem ? Do you have any other method to install pyLDAvis because pip is not working?

**Comment by bmabey** [comment]
We are working on removing `scikit-bio` as a dependency.

**Comment by kevinbsc** [comment]
Great idea. scikit-bio is no longer available for Python 2. Thanks.

**Comment by bmabey** [comment]
This was actually resolved last month and a release was made https://github.com/bmabey/pyLDAvis/commit/1f92fbeae07144cb5c1ccc06928e2620f2f3a063
