### ISSUE TITLE
Topic number in pyLDAvis different from that in gensim.ldamodel

### ISSUE THREAD

**Issue by Ronggui** [bmabey/pyLDAvis#59]
For instance, the topic 19 in pyLDAvis refers to topic 29 in the original lda model.

Is there a way to keep the topic numbering order the same as lda model?

**Comment by bmabey** [comment]
On 4/10/16 1:04 PM, Ronggui Huang wrote:
>
> For instance, the topic 19 in pyLDAvis refers to topic 29 in the 
> original lda model.
>
> Is there a way to keep the topic numbering order the same as lda model?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/bmabey/pyLDAvis/issues/59>
>
Having the topics ranked by prevalence is by design and comes from the 
LDAvis package and paper. One nice thing about this is that different 
fits will have more or less stable topics. Right now there is no way to 
turn this off.

**Comment by Ronggui** [comment]
Is it possible (necessary) to return a dict to show the correspondence between the original numbers and the new numbers?

**Comment by bmabey** [comment]
The most recent release provides an option to preserve the original ordering. See the docs for the prepare function for more details. 

I'm away from my computer now but I believe the ordering is also returned the data that comes from the prepare function.

**Comment by Tesfamariam** [comment]
I am having the following error?
TypeError: eval() got an unexpected keyword argument 'inplace'

**Comment by bmabey** [comment]
I have no idea, are you?
