### ISSUE TITLE
Visualizing topics without corpus

### ISSUE THREAD

**Issue by nguyenhoan1988** [bmabey/pyLDAvis#70]
I train a `gensim` LDA model with a very large corpus (almost 100M documents), and I train it in the **streaming fashion**. Therefore, I cannot reproduce the corpus that is needed for the `prepare` method of `pyLDAvis`.

But the `corpus` is needed in this method. I try to fake a small corpus with a sample of the training data but it does not work, and give me the following exception:
```
anaconda/lib/python2.7/site-packages/pyLDAvis/gensim.pyc in _extract_data(topic_model, corpus, dictionary, doc_topic_dists)
     26    beta = 0.01
     27    fnames_argsort = np.asarray(list(dictionary.token2id.values()), dtype=np.int_)
---> 28    term_freqs = corpus_csc.sum(axis=1).A.ravel()[fnames_argsort]
     29    term_freqs[term_freqs == 0] = beta
     30    doc_lengths = corpus_csc.sum(axis=0).A.ravel()

IndexError: index 66999 is out of bounds for axis 1 with size 66988
```

Is there any methods to work around this problem?

**Comment by bmabey** [comment]
The visualization itself doesn't need a corpus but it does require counts that are calculated using the corpus. All of that logic for gensim happens [here](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/gensim.py#L15-L62).

To work around this you would need to do similar counts in a streaming fashion and call `pyLDAvis.prepare` directly. The docs explain what is needed for `pyLDAvis.prepare`.
