### ISSUE TITLE
line 48 of gensim module has incorrect logic

### ISSUE THREAD

**Issue by ggilling** [bmabey/pyLDAvis#73]
I just got a comical "25!=25" error because of this line:

assert doc_topic_dists.shape[1] == num_topics, 'Document topics and number of topics do not match {} != {}'.format(doc_topic_dists.shape[0], num_topics)

**Comment by bmabey** [comment]
Did you happen to break into a debug session to see if it is a type issue? I'm surprised no one else has ran into this.

**Comment by bmabey** [comment]
nm, I didn't see the index problem. I'll fix that, thanks for the report.
