### ISSUE TITLE
TypeError: cannot sort an Index object in-place, use sort_values instead : For Gensim LDA Model

### ISSUE THREAD

**Issue by budhiraja** [bmabey/pyLDAvis#74]
For Gensim LDA model with 150K vocab size, the following error is thrown when I do the following:

```
model_filename = "150k_LdaModel_topics_"+ topics +"_passes_"+passes +".model"

dictionary = gensim.corpora.Dictionary.load('LDADictSpecialRemoved150k.dict')
corpus = gensim.corpora.MmCorpus('LDACorpusSpecialRemoved150k.mm')
ldamodel = gensim.models.ldamodel.LdaModel.load(model_filename)

import pyLDAvis.gensim
vis = pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)
pyLDAvis.save_html(vis, "topic_viz_"+topics+"_passes_"+passes+".html")
```

```
Traceback (most recent call last):
  File "create_vis.py", line 36, in <module>
    vis = pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)
  File "/local/lib/python2.7/site-packages/pyLDAvis/gensim.py", line 110, in prepare
    return vis_prepare(**opts)
  File "/local/lib/python2.7/site-packages/pyLDAvis/_prepare.py", line 398, in prepare
    token_table        = _token_table(topic_info, term_topic_freq, vocab, term_frequency)
  File "/local/lib/python2.7/site-packages/pyLDAvis/_prepare.py", line 267, in _token_table
    term_ix.sort()
  File "/local/lib/python2.7/site-packages/pandas/indexes/base.py", line 1703, in sort
    raise TypeError("cannot sort an Index object in-place, use "
TypeError: cannot sort an Index object in-place, use sort_values instead

```

**Comment by napsternxg** [comment]
I believe this can be fixed by using: 
`term_ix = np.sort(topic_info.index.unique().values)`
https://github.com/bmabey/pyLDAvis/blob/1.4.0/pyLDAvis/_prepare.py#L220

**Comment by budhiraja** [comment]
So I will have build a version by changing it in the code?

**Comment by napsternxg** [comment]
I have created a pull request with the fix. @bmabey you might want to merge this and update the releases so that people can install is using pip.

**Comment by jc-healy** [comment]
Hi, I gave this change a try and it didn't seem to fix the error on my system.  Here's what my error looks like with the new change.  

/Users/jchealy/anaconda/envs/datascience/lib/python3.5/site-packages/pyLDAvis/_prepare.py in _token_table(topic_info, term_topic_freq, vocab, term_frequency)
    265    # term-topic frequency table of unique terms across all topics and all values of lambda
    266    term_ix = topic_info.index.unique()
--> 267    term_ix = np.sort(term_ix.values)
    268    top_topic_terms_freq = term_topic_freq[term_ix]
    269    # use the new ordering for the topics

/Users/jchealy/anaconda/envs/datascience/lib/python3.5/site-packages/pandas/indexes/base.py in sort(self, *args, **kwargs)
   1701 
   1702     def sort(self, *args, **kwargs):
-> 1703         raise TypeError("cannot sort an Index object in-place, use "
   1704                         "sort_values instead")
   1705 

TypeError: cannot sort an Index object in-place, use sort_values instead
