### ISSUE TITLE
Microsoft Visual C++ 10.0 is required

### ISSUE THREAD

**Issue by shamitb** [bmabey/pyLDAvis#9]
customize MSVCCompiler
    customize MSVCCompiler using build_ext
    No module named 'numpy.distutils.msvccompiler' in numpy.distutils; trying fr
om distutils
    customize MSVCCompiler
    Missing compiler_cxx fix for MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'numexpr.interpreter' extension
    compiling C sources
    Warning: Assuming default configuration (numexpr\tests/{setup_tests,setup}.p
y was not found)error: Microsoft Visual C++ 10.0 is required (Unable to find vcv
arsall.bat).

**Comment by bmabey** [comment]
If you are compiling all of the deps from source on Windows this may be true. `pyLDAvis` has no C code in itself so it is all in it's deps. If you were use anaconda or similar distribution I imagine no compiler would be required.
