### ISSUE TITLE
Pandas Deprecation Warning

### ISSUE THREAD

**Issue by goonmeet** [bmabey/pyLDAvis#96]
pyLDAvis/_prepare.py

topic_term_dists = topic_term_dists.ix[topic_order]

.ix is deprecated in Pandas now. Can use:

topic_term_dists = topic_term_dists**.iloc**[topic_order]

**Comment by bbennett36** [comment]
Running into the same issue.

```
/anaconda3/lib/python3.6/site-packages/pyLDAvis/_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing
```

**Comment by jacobthill** [comment]
I have the same problem. 

Warning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

**Comment by bmabey** [comment]
This has been fixed but I still need to make a release. If you direct pip/conda to install from github this message should go away.

**Comment by jacobthill** [comment]
thanks, i'll try that

**Comment by ShaikhaV** [comment]
@bmabey What is it we can download to make this message go away?

**Comment by Diyago** [comment]
The message is a still shown:

``` python
\pyLDAvis\_prepare.py:387: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing
```

Everything must up to date

**Comment by bmabey** [comment]
This has been fixed for a while in the git repo but I just released a pip package with the fix.
